// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbtgeioqmyuunpepdpvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidGdlaW9xbXl1dW5wZXBkcHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzkzNzcsImV4cCI6MjA3MjI1NTM3N30.JpEjX3BVY6yqhNPKPQg6TV__hI7r5QsxArvKx8mBO9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});